import React, { useState } from 'react';
import './Dashboards.css';
import Payments from '../Dashboards/Payments';
import Subscriptions from '../Dashboards/Subscriptions';
import OpenAi from '../Dashboards/OpenAi';
import ContentItems from '../Dashboards/ContentItems';
import Documents from '../Dashboards/Documents';
import Crud from '../Dashboards/Crud';
import Pandp from '../Dashboards/Pandp';
import Tc from '../Dashboards/Tc';
import { MdArrowOutward } from "react-icons/md";

function Dashboard() {
  const [selectedItem, setSelectedItem] = useState(null);
  const [showArrow, setShowArrow] = useState({
    Payments: false,
    Subscriptions: false,
    'Open AI Integration': false,
    'Content items': false,
    Documents: false,
    CRUD: false,
    'Privacy policy': false,
    'Terms and conditions': false,
  });

  const handleItemClick = (itemName) => {
    setSelectedItem(itemName);
  };

  const handleMouseEnter = (itemName) => {
    setShowArrow(prevState => ({ ...prevState, [itemName]: true }));
  };

  const handleMouseLeave = (itemName) => {
    setShowArrow(prevState => ({ ...prevState, [itemName]: false }));
  };

  const renderSelectedItemPage = () => {
    switch (selectedItem) {
      case 'Payments':
        return <Payments />;
      case 'Subscriptions':
        return <Subscriptions />;
      case 'OpenAI Integration':
        return <OpenAi />;
      case 'Content items':
        return <ContentItems />;
      case 'Documents':
        return <Documents />;
      case 'CRUD':
        return <Crud />;
      case 'Privacy policy':
        return <Pandp />;
      case 'Terms and conditions':
        return <Tc />;
      default:
        return null;
    }
  };

  return (
    <div>
      {selectedItem ? (
        <div className="selected-item-page">
          <button onClick={() => setSelectedItem(null)}>Back to Dashboard</button>
          {renderSelectedItemPage()}
        </div>
      ) : (
        <div className="dashboard-grid">
          <div className="grid-item" onClick={() => handleItemClick('Payments')} onMouseEnter={() => handleMouseEnter('Payments')} onMouseLeave={() => handleMouseLeave('Payments')}>
            <h2>Payments {showArrow.Payments && <MdArrowOutward />}</h2>
            Example of single payment form.
          </div>
          <div className="grid-item" onClick={() => handleItemClick('Subscriptions')} onMouseEnter={() => handleMouseEnter('Subscriptions')} onMouseLeave={() => handleMouseLeave('Subscriptions')}>
            <h2>Subscriptions {showArrow.Subscriptions && <MdArrowOutward />}</h2>
            Example of subscription management.
          </div>
          <div className="grid-item" onClick={() => handleItemClick('OpenAI Integration')} onMouseEnter={() => handleMouseEnter('Open AI Integration')} onMouseLeave={() => handleMouseLeave('Open AI Integration')}>
            <h2>Open AI integration {showArrow['Open AI Integration'] && <MdArrowOutward />}</h2>
            SaaS ideas generator as an example of Open AI integration.
          </div>
          <div className="grid-item" onClick={() => handleItemClick('Content items')} onMouseEnter={() => handleMouseEnter('Content items')} onMouseLeave={() => handleMouseLeave('Content items')}>
            <h2>Content items {showArrow['Content items'] && <MdArrowOutward />}</h2>
            Demo of the Contentful integration.
          </div>
          <div className="grid-item" onClick={() => handleItemClick('Documents')} onMouseEnter={() => handleMouseEnter('Documents')} onMouseLeave={() => handleMouseLeave('Documents')}>
            <h2>Documents {showArrow.Documents && <MdArrowOutward />}</h2>
            File upload and asset management example.
          </div>
          <div className="grid-item" onClick={() => handleItemClick('CRUD')} onMouseEnter={() => handleMouseEnter('CRUD')} onMouseLeave={() => handleMouseLeave('CRUD')}>
            <h2>CRUD {showArrow.CRUD && <MdArrowOutward />}</h2>
            Create-Read-Update-Delete module example that is generated by built-in generator.
          </div>
          <div className="grid-item" onClick={() => handleItemClick('Privacy policy')} onMouseEnter={() => handleMouseEnter('Privacy policy')} onMouseLeave={() => handleMouseLeave('Privacy policy')}>
            <h2>Privacy policy {showArrow['Privacy policy'] && <MdArrowOutward />}</h2>
            Your Privacy Policy component goes here.
          </div>
          <div className="grid-item" onClick={() => handleItemClick('Terms and conditions')} onMouseEnter={() => handleMouseEnter('Terms and conditions')} onMouseLeave={() => handleMouseLeave('Terms and conditions')}>
            <h2>Terms and conditions {showArrow['Terms and conditions'] && <MdArrowOutward />}</h2>
            Your Terms and Conditions component goes here.
          </div>
        </div>
      )}
    </div>
  );
}

export default Dashboard;
